// Textos fijos de la interfaz en cada idioma.
// Tus datos personales van en data/config.js, no aquí.

const TEXTOS = {
  es: {
    nav_servicios: "Servicios",
    nav_proyectos: "Proyectos",
    nav_experiencia: "Experiencia",
    nav_blog: "Blog",
    nav_testimonios: "Testimonios",
    nav_sobre: "Perfil",
    nav_contacto: "Contacto",
    menu: "Menú",
    tema: "Cambiar tema claro/oscuro",

    disponible: "Disponible para nuevos proyectos y oportunidades",
    ver_proyectos: "Ver proyectos",
    contactame: "Contacto",
    descargar_cv: "Descargar CV",
    cv_titulo: "Hoja de vida",
    cv_texto: "Experiencia, proyectos, formación y habilidades en una sola página.",
    cv_pdf: "Descargar PDF",
    cv_ver: "Ver en línea",
    destacado: "Proyecto destacado",
    cifra_proyectos: "proyectos",
    cifra_tecnologias: "tecnologías",
    cifra_plataformas: "plataformas",
    cifra_servicios: "servicios",

    servicios_titulo: "Soluciones que desarrollo",
    servicios_bajada: "Inteligencia artificial y software a la medida para empresas, emprendimientos e instituciones: desde la automatización de reportes hasta la integración con dispositivos físicos.",
    servicios_otro: "¿Su necesidad no aparece en la lista? Evalúo la viabilidad técnica de cada proyecto y propongo una solución a la medida.",
    servicios_cotizar: "Solicitar una propuesta",
    servicio_ejemplo: "Caso de referencia",
    metodologia_titulo: "Cómo convierto una idea en una solución",

    proyectos_titulo: "Proyectos seleccionados",
    proyectos_bajada: "Casos de estudio de soluciones diseñadas, desarrolladas y puestas en marcha de principio a fin: el problema, la solución, la arquitectura y los resultados.",
    todos: "Todos",
    tipo_web: "Web",
    tipo_escritorio: "Escritorio",
    tipo_movil: "Móvil",
    tipo_ia: "IA y datos",
    chip_ia: "Hecho con IA",
    ficha_desarrollo: "Desarrollo",
    ficha_con_ia: "Asistido por IA",
    ver_proyecto: "Ver caso de estudio",

    experiencia_titulo: "Experiencia y formación",
    experiencia_bajada: "Trayectoria que integra ingeniería electrónica, infraestructura de redes y desarrollo de soluciones con inteligencia artificial.",
    formacion: "Formación académica",
    certificaciones: "Certificaciones",

    blog_titulo: "Artículos técnicos",
    blog_bajada: "Publicaciones sobre inteligencia artificial, automatización y desarrollo de software.",
    testimonios_titulo: "Lo que dicen quienes han trabajado conmigo",
    testimonio_proyecto: "Ver el proyecto",
    blog_vacio: "Próximamente se publicarán los primeros artículos.",

    sobre_titulo: "Perfil profesional",
    stack_titulo: "Competencias técnicas",
    habilidades: "Habilidades",
    tecnologias_proyectos: "Tecnologías utilizadas en los proyectos",
    pendiente: "Sección en construcción.",

    contacto_titulo: "Conversemos sobre su proyecto",
    contacto_texto: "Automatización de reportes, sistemas de gestión, aplicaciones a la medida u oportunidades laborales: escríbame y le responderé a la brevedad.",
    escribeme: "Enviar un correo",
    escribir_whatsapp: "Escribir por WhatsApp",
    whatsapp_mensaje: "Hola, Andrey. Vi su portafolio y me gustaría conversar sobre un proyecto.",
    correo_asunto: "Consulta desde su portafolio",
    correo_cuerpo: "Hola, Andrey:\n\nQué necesito:\n\nPlazo estimado:\n\nPresupuesto aproximado (opcional):\n\nGracias.",
    copiar_correo: "Copiar correo",
    copiado: "¡Copiado!",

    ficha_fecha: "Fecha",
    ficha_tipo: "Tipo",
    ficha_estado: "Estado",
    ficha_tecnologias: "Tecnologías",
    ficha_temas: "Temas",
    ficha_enlaces: "Enlaces",
    ver_demo: "Ver demostración",
    ver_codigo: "Ver código",
    otros_proyectos: "Otros proyectos",
    volver: "← Volver al inicio",
    no_encontrado: "Página no encontrada",
    cerrar: "Cerrar",
    anterior: "Anterior",
    siguiente: "Siguiente",

    derechos: "Desarrollado en Colombia",
    arriba: "Volver arriba",
    pie_frase: "Construyo soluciones con inteligencia artificial, automatización y datos para empresas y emprendimientos.",
    pie_navegacion: "Navegación",
    pie_contacto: "Contacto",
  },
  en: {
    nav_servicios: "Services",
    nav_proyectos: "Projects",
    nav_experiencia: "Experience",
    nav_blog: "Blog",
    nav_testimonios: "Testimonials",
    nav_sobre: "Profile",
    nav_contacto: "Contact",
    menu: "Menu",
    tema: "Toggle light/dark theme",

    disponible: "Available for new projects and opportunities",
    ver_proyectos: "View projects",
    contactame: "Contact",
    descargar_cv: "Download CV",
    cv_titulo: "Resume",
    cv_texto: "Experience, projects, education and skills on a single page.",
    cv_pdf: "Download PDF",
    cv_ver: "View online",
    destacado: "Featured project",
    cifra_proyectos: "projects",
    cifra_tecnologias: "technologies",
    cifra_plataformas: "platforms",
    cifra_servicios: "services",

    servicios_titulo: "Solutions I build",
    servicios_bajada: "Artificial intelligence and custom software for companies, growing businesses and institutions: from report automation to integration with physical devices.",
    servicios_otro: "Don't see what you need? I assess the technical feasibility of every project and propose a tailored solution.",
    servicios_cotizar: "Request a proposal",
    servicio_ejemplo: "Reference case",
    metodologia_titulo: "How I turn an idea into a solution",

    proyectos_titulo: "Selected projects",
    proyectos_bajada: "Case studies of solutions designed, built and launched end to end: the problem, the solution, the architecture and the results.",
    todos: "All",
    tipo_web: "Web",
    tipo_escritorio: "Desktop",
    tipo_movil: "Mobile",
    tipo_ia: "AI & data",
    chip_ia: "Built with AI",
    ficha_desarrollo: "Development",
    ficha_con_ia: "AI-assisted",
    ver_proyecto: "View case study",

    experiencia_titulo: "Experience & education",
    experiencia_bajada: "A career that combines electronics engineering, network infrastructure and artificial intelligence solutions.",
    formacion: "Education",
    certificaciones: "Certifications",

    blog_titulo: "Technical articles",
    blog_bajada: "Articles on artificial intelligence, automation and software development.",
    testimonios_titulo: "What people I have worked with say",
    testimonio_proyecto: "View the project",
    blog_vacio: "The first articles will be published soon.",

    sobre_titulo: "Professional profile",
    stack_titulo: "Technical skills",
    habilidades: "Skills",
    tecnologias_proyectos: "Technologies used in the projects",
    pendiente: "Section under construction.",

    contacto_titulo: "Let's talk about your project",
    contacto_texto: "Report automation, management systems, custom applications or job opportunities: send me a message and I will get back to you shortly.",
    escribeme: "Send an email",
    escribir_whatsapp: "Message on WhatsApp",
    whatsapp_mensaje: "Hi Andrey, I saw your portfolio and would like to talk about a project.",
    correo_asunto: "Inquiry from your portfolio",
    correo_cuerpo: "Hi Andrey,\n\nWhat I need:\n\nEstimated timeline:\n\nApproximate budget (optional):\n\nThank you.",
    copiar_correo: "Copy email",
    copiado: "Copied!",

    ficha_fecha: "Date",
    ficha_tipo: "Type",
    ficha_estado: "Status",
    ficha_tecnologias: "Tech stack",
    ficha_temas: "Topics",
    ficha_enlaces: "Links",
    ver_demo: "View demo",
    ver_codigo: "View code",
    otros_proyectos: "More projects",
    volver: "← Back to home",
    no_encontrado: "Page not found",
    cerrar: "Close",
    anterior: "Previous",
    siguiente: "Next",

    derechos: "Built in Colombia",
    arriba: "Back to top",
    pie_frase: "I build artificial intelligence, automation and data solutions for companies and growing businesses.",
    pie_navegacion: "Navigation",
    pie_contacto: "Contact",
  },
};
