// Textos fijos de la interfaz en cada idioma.
// Tus datos personales van en data/config.js, no aquí.

const TEXTOS = {
  es: {
    nav_servicios: "Servicios",
    nav_proyectos: "Proyectos",
    nav_experiencia: "Experiencia",
    nav_blog: "Blog",
    nav_testimonios: "Testimonios",
    nav_sobre: "Perfil",
    nav_contacto: "Contacto",
    menu: "Menú",
    tema: "Cambiar tema claro/oscuro",

    disponible: "Disponible para nuevos proyectos y oportunidades",
    ver_proyectos: "Ver proyectos",
    contactame: "Contacto",
    descargar_cv: "Descargar CV",
    cv_titulo: "Hoja de vida",
    cv_texto: "Experiencia, proyectos, formación y habilidades en una sola página.",
    cv_pdf: "Descargar PDF",
    cv_ver: "Ver en línea",
    destacado: "Proyecto destacado",
    cifra_proyectos: "proyectos",
    cifra_tecnologias: "tecnologías",
    cifra_plataformas: "plataformas",
    cifra_servicios: "servicios",

    servicios_titulo: "Soluciones que desarrollo",
    servicios_bajada: "Inteligencia artificial y software a la medida para empresas, emprendimientos e instituciones: desde la automatización de reportes hasta la integración con dispositivos físicos.",
    servicios_otro: "¿Su necesidad no aparece en la lista? Evalúo la viabilidad técnica de cada proyecto y propongo una solución a la medida.",
    servicios_cotizar: "Solicitar una propuesta",
    servicio_ejemplo: "Caso de referencia",
    metodologia_titulo: "Cómo convierto una idea en una solución",

    proyectos_titulo: "Proyectos seleccionados",
    proyectos_bajada: "Casos de estudio de soluciones diseñadas, desarrolladas y puestas en marcha de principio a fin: el problema, la solución, la arquitectura y los resultados.",
    todos: "Todos",
    tipo_web: "Web",
    tipo_escritorio: "Escritorio",
    tipo_movil: "Móvil",
    tipo_ia: "IA y datos",
    chip_ia: "Hecho con IA",
    ficha_desarrollo: "Desarrollo",
    ficha_con_ia: "Asistido por IA",
    ver_proyecto: "Ver caso de estudio",

    experiencia_titulo: "Experiencia y formación",
    experiencia_bajada: "Trayectoria que integra ingeniería electrónica, infraestructura de redes y desarrollo de soluciones con inteligencia artificial.",
    formacion: "Formación académica",
    certificaciones: "Certificaciones",

    blog_titulo: "Artículos técnicos",
    blog_bajada: "Publicaciones sobre inteligencia artificial, automatización y desarrollo de software.",
    testimonios_titulo: "Lo que dicen quienes han trabajado conmigo",
    testimonio_proyecto: "Ver el proyecto",
    blog_vacio: "Próximamente se publicarán los primeros artículos.",

    sobre_titulo: "Perfil profesional",
    stack_titulo: "Competencias técnicas",
    habilidades: "Habilidades",
    tecnologias_proyectos: "Tecnologías utilizadas en los proyectos",
    pendiente: "Sección en construcción.",

    contacto_titulo: "Conversemos sobre su proyecto",
    contacto_texto: "Automatización de reportes, sistemas de gestión, aplicaciones a la medida u oportunidades laborales: escríbame y le responderé a la brevedad.",
    escribeme: "Enviar un correo",
    escribir_whatsapp: "Escribir por WhatsApp",
    whatsapp_mensaje: "Hola, Andrey. Vi su portafolio y me gustaría conversar sobre un proyecto.",
    correo_asunto: "Consulta desde su portafolio",
    correo_cuerpo: "Hola, Andrey:\n\nQué necesito:\n\nPlazo estimado:\n\nPresupuesto aproximado (opcional):\n\nGracias.",
    copiar_correo: "Copiar correo",
    copiado: "¡Copiado!",

    ficha_fecha: "Fecha",
    ficha_tipo: "Tipo",
    ficha_estado: "Estado",
    ficha_tecnologias: "Tecnologías",
    ficha_temas: "Temas",
    ficha_enlaces: "Enlaces",
    ver_demo: "Ver demostración",
    ver_codigo: "Ver código",
    otros_proyectos: "Otros proyectos",
    volver: "← Volver al inicio",
    no_encontrado: "Página no encontrada",
    cerrar: "Cerrar",
    anterior: "Anterior",
    siguiente: "Siguiente",

    derechos: "Desarrollado en Colombia",
    arriba: "Volver arriba",
    pie_frase: "Construyo soluciones con inteligencia artificial, automatización y datos para empresas y emprendimientos.",
    pie_navegacion: "Navegación",
    pie_contacto: "Contacto",

    asis_flotante: "Escríbame",
    asis_abrir: "Contar mi proyecto al asistente",
    asis_titulo: "Asistente de Andrey",
    asis_estado: "Responde al instante · con IA",
    asis_saludo: "Hola, es un gusto saludarle. Soy el asistente virtual de Andrey Martínez. ¿En qué le puedo ayudar hoy?\n\nCuénteme brevemente su proyecto y le haré unas preguntas para que Andrey le contacte por WhatsApp con todo el contexto.",
    asis_op1: "Una aplicación",
    asis_op2: "Una página web",
    asis_op3: "Automatizar con IA",
    asis_op4: "Reportes y análisis de datos",
    asis_escribir: "Escriba su mensaje…",
    asis_enviar: "Enviar",
    asis_directo: "Prefiero escribir directo por WhatsApp",
    asis_privacidad: "Sus respuestas se procesan con IA solo para preparar el resumen. No comparta datos sensibles.",
    asis_resumen: "Resumen para Andrey",
    asis_enviar_wa: "Enviar a Andrey por WhatsApp",
    asis_seguir: "Agregar algo más",
    asis_reiniciar: "Empezar de nuevo",
    asis_enviado: "Listo. Si WhatsApp no se abrió, use el botón de nuevo. Andrey le responderá a la brevedad.",
    asis_seguir_msg: "Claro, ¿qué más le gustaría agregar?",
    asis_wa_inicio: "Hola, Andrey. Le escribo desde su portafolio; este es el resumen de lo que necesito:",
    asis_p_necesidad: "¿Qué necesita? Por ejemplo, una aplicación, una página web o automatizar una tarea.",
    asis_p_negocio: "Entendido. ¿Para qué tipo de negocio o institución es?",
    asis_p_situacionActual: "¿Cómo maneja ese proceso hoy? (cuaderno, Excel, otro sistema, nada…)",
    asis_p_usuarios: "¿Cuántas personas lo usarían y desde dónde: celular, computador o ambos?",
    asis_p_plazo: "¿Para cuándo lo necesita?",
    asis_p_presupuesto: "¿Tiene un presupuesto aproximado? Si lo prefiere, escriba «por definir».",
    asis_p_nombre: "Por último, ¿cuál es su nombre (y el de su empresa, si aplica)?",
    asis_p_fin: "Muchas gracias. Abajo encontrará el resumen; envíelo a Andrey por WhatsApp y él le responderá con una propuesta.",
    asis_c_nombre: "Nombre",
    asis_c_negocio: "Negocio",
    asis_c_necesidad: "Necesita",
    asis_c_situacionActual: "Hoy lo maneja",
    asis_c_usuarios: "Usuarios",
    asis_c_plataforma: "Plataforma",
    asis_c_plazo: "Plazo",
    asis_c_presupuesto: "Presupuesto",
    asis_c_notas: "Detalles",
  },
  en: {
    nav_servicios: "Services",
    nav_proyectos: "Projects",
    nav_experiencia: "Experience",
    nav_blog: "Blog",
    nav_testimonios: "Testimonials",
    nav_sobre: "Profile",
    nav_contacto: "Contact",
    menu: "Menu",
    tema: "Toggle light/dark theme",

    disponible: "Available for new projects and opportunities",
    ver_proyectos: "View projects",
    contactame: "Contact",
    descargar_cv: "Download CV",
    cv_titulo: "Resume",
    cv_texto: "Experience, projects, education and skills on a single page.",
    cv_pdf: "Download PDF",
    cv_ver: "View online",
    destacado: "Featured project",
    cifra_proyectos: "projects",
    cifra_tecnologias: "technologies",
    cifra_plataformas: "platforms",
    cifra_servicios: "services",

    servicios_titulo: "Solutions I build",
    servicios_bajada: "Artificial intelligence and custom software for companies, growing businesses and institutions: from report automation to integration with physical devices.",
    servicios_otro: "Don't see what you need? I assess the technical feasibility of every project and propose a tailored solution.",
    servicios_cotizar: "Request a proposal",
    servicio_ejemplo: "Reference case",
    metodologia_titulo: "How I turn an idea into a solution",

    proyectos_titulo: "Selected projects",
    proyectos_bajada: "Case studies of solutions designed, built and launched end to end: the problem, the solution, the architecture and the results.",
    todos: "All",
    tipo_web: "Web",
    tipo_escritorio: "Desktop",
    tipo_movil: "Mobile",
    tipo_ia: "AI & data",
    chip_ia: "Built with AI",
    ficha_desarrollo: "Development",
    ficha_con_ia: "AI-assisted",
    ver_proyecto: "View case study",

    experiencia_titulo: "Experience & education",
    experiencia_bajada: "A career that combines electronics engineering, network infrastructure and artificial intelligence solutions.",
    formacion: "Education",
    certificaciones: "Certifications",

    blog_titulo: "Technical articles",
    blog_bajada: "Articles on artificial intelligence, automation and software development.",
    testimonios_titulo: "What people I have worked with say",
    testimonio_proyecto: "View the project",
    blog_vacio: "The first articles will be published soon.",

    sobre_titulo: "Professional profile",
    stack_titulo: "Technical skills",
    habilidades: "Skills",
    tecnologias_proyectos: "Technologies used in the projects",
    pendiente: "Section under construction.",

    contacto_titulo: "Let's talk about your project",
    contacto_texto: "Report automation, management systems, custom applications or job opportunities: send me a message and I will get back to you shortly.",
    escribeme: "Send an email",
    escribir_whatsapp: "Message on WhatsApp",
    whatsapp_mensaje: "Hi Andrey, I saw your portfolio and would like to talk about a project.",
    correo_asunto: "Inquiry from your portfolio",
    correo_cuerpo: "Hi Andrey,\n\nWhat I need:\n\nEstimated timeline:\n\nApproximate budget (optional):\n\nThank you.",
    copiar_correo: "Copy email",
    copiado: "Copied!",

    ficha_fecha: "Date",
    ficha_tipo: "Type",
    ficha_estado: "Status",
    ficha_tecnologias: "Tech stack",
    ficha_temas: "Topics",
    ficha_enlaces: "Links",
    ver_demo: "View demo",
    ver_codigo: "View code",
    otros_proyectos: "More projects",
    volver: "← Back to home",
    no_encontrado: "Page not found",
    cerrar: "Close",
    anterior: "Previous",
    siguiente: "Next",

    derechos: "Built in Colombia",
    arriba: "Back to top",
    pie_frase: "I build artificial intelligence, automation and data solutions for companies and growing businesses.",
    pie_navegacion: "Navigation",
    pie_contacto: "Contact",

    asis_flotante: "Message me",
    asis_abrir: "Tell the assistant about my project",
    asis_titulo: "Andrey's assistant",
    asis_estado: "Replies instantly · AI-powered",
    asis_saludo: "Hello, it's a pleasure to greet you. I'm Andrey Martínez's virtual assistant. How can I help you today?\n\nTell me briefly about your project and I'll ask a few questions so Andrey can reach you on WhatsApp with full context.",
    asis_op1: "An application",
    asis_op2: "A website",
    asis_op3: "Automate with AI",
    asis_op4: "Reports and data analysis",
    asis_escribir: "Type your message…",
    asis_enviar: "Send",
    asis_directo: "I'd rather message directly on WhatsApp",
    asis_privacidad: "Your answers are processed with AI only to prepare the summary. Please don't share sensitive data.",
    asis_resumen: "Summary for Andrey",
    asis_enviar_wa: "Send to Andrey on WhatsApp",
    asis_seguir: "Add something else",
    asis_reiniciar: "Start over",
    asis_enviado: "Done. If WhatsApp didn't open, use the button again. Andrey will get back to you shortly.",
    asis_seguir_msg: "Of course, what else would you like to add?",
    asis_wa_inicio: "Hi Andrey, I'm writing from your portfolio; here is a summary of what I need:",
    asis_p_necesidad: "What do you need? For example, an application, a website or automating a task.",
    asis_p_negocio: "Got it. What type of business or institution is it for?",
    asis_p_situacionActual: "How do you handle that process today? (notebook, Excel, another system, nothing…)",
    asis_p_usuarios: "How many people would use it, and from where: phone, computer or both?",
    asis_p_plazo: "When do you need it?",
    asis_p_presupuesto: "Do you have an approximate budget? If you prefer, write \"to be defined\".",
    asis_p_nombre: "Finally, what is your name (and your company's, if applicable)?",
    asis_p_fin: "Thank you very much. Below you'll find the summary; send it to Andrey on WhatsApp and he'll reply with a proposal.",
    asis_c_nombre: "Name",
    asis_c_negocio: "Business",
    asis_c_necesidad: "Needs",
    asis_c_situacionActual: "Current process",
    asis_c_usuarios: "Users",
    asis_c_plataforma: "Platform",
    asis_c_plazo: "Timeline",
    asis_c_presupuesto: "Budget",
    asis_c_notas: "Details",
  },
};
